export const GET_MUSIC_LIST_ACTION = 'GET_MUSIC_LIST_ACTION'
export const GET_MUSIC_LIST_SUCCESS_ACTION = 'GET_MUSIC_LIST_SUCCESS_ACTION'
export const GET_MUSIC_LIST_FAILURE_ACTION = 'GET_MUSIC_LIST_FAILURE_ACTION'